from .emb_generator_bankruptcy import get_emb_features_bankruptcy
from .emb_generator_boxing1 import get_emb_features_boxing1
from .emb_generator_boxing2 import get_emb_features_boxing2
from .emb_generator_colic import get_emb_features_colic
from .emb_generator_credit import get_emb_features_credit